apiVersion: apps/v1
kind: Deployment
metadata:
  name: environment-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: environment-builder
  template:
    metadata:
      labels:
        app: environment-builder
    spec:
      containers:
        - name: environment-builder
          image: 630r63/environment-builder-validator:1.1
          ports:
            - containerPort: 8080