technologies:
  - name: docker
    version: "29"

  - name: python
    version: "3.13"

  - name: java
    version: "17"

  - name: nodejs
    version: "22"

  - name: mysql
    version: "8.4"

  - name: nginx
    version: "1.28"

  - name: git
    version: "2.51"

  - name: redis
    version: "8"