---
- name: Instaleaza tehnologiile cerute
  hosts: environment_servers

  vars:
    technologies: {}

  roles:
    - role: docker
    - role: python
    - role: java
    - role: node
    - role: mysql
    - role: nginx
    - role: git
    - role: redis